import {
  UserPlus,
  FileUp,
  Brain,
  Map,
  Mic,
  Trophy,
} from "lucide-react";

function HowItWorks() {
  const steps = [
    {
      icon: <UserPlus size={36} />,
      title: "Create an Account",
      description: "Sign up to unlock personalized AI career tools.",
    },
    {
      icon: <FileUp size={36} />,
      title: "Upload Your Resume",
      description: "Upload your resume for AI-powered analysis and ATS scoring.",
    },
    {
      icon: <Brain size={36} />,
      title: "Get Career Guidance",
      description: "Receive AI recommendations based on your goals and skills.",
    },
    {
      icon: <Map size={36} />,
      title: "Follow Your Roadmap",
      description: "Learn through a personalized roadmap generated by AI.",
    },
    {
      icon: <Mic size={36} />,
      title: "Practice Interviews",
      description: "Prepare with topic, role, or company-based AI interviews.",
    },
    {
      icon: <Trophy size={36} />,
      title: "Achieve Your Goal",
      description: "Track your progress and become placement-ready.",
    },
  ];

  return (
    <section className="py-24 bg-slate-900 text-white">

      <div className="max-w-7xl mx-auto px-8">

        <h2 className="text-5xl font-bold text-center">
          How CareerPilot AI Works
        </h2>

        <p className="text-center text-slate-400 mt-4 max-w-3xl mx-auto">
          Your complete AI-powered journey from career planning to placement success.
        </p>

        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8 mt-16">

          {steps.map((step, index) => (
            <div
              key={index}
              className="bg-slate-800 rounded-2xl p-8 hover:scale-105 hover:bg-slate-700 transition duration-300"
            >

              <div className="text-cyan-400 mb-5">
                {step.icon}
              </div>

              <h3 className="text-2xl font-bold">
                {step.title}
              </h3>

              <p className="text-slate-400 mt-4">
                {step.description}
              </p>

            </div>
          ))}

        </div>

      </div>

    </section>
  );
}

export default HowItWorks;